### ISSUE TITLE
Error: Cannot find module '@arbennett\base16-nord\package.json'

### ISSUE THREAD

**Issue by euglevi** [arbennett/jupyterlab-themes#12]
Both through "labextension install" and npm, the installation fails with this error: `Error: Cannot find module '@arbennett\base16-nord\package.json`. Any ideas on what might it be?

**Comment by arbennett** [comment]
Dang, I got super frustrated with this problem myself, and ended up fixing it by deleting a number of yarn and node directories, but I don't quite know which solved it. I wish I had better advice, but maybe try removing `~/.yarn` and `~/.npm`? This might cause other problems though if other programs rely on things installed there. Let me know if that solves things, otherwise I can try to re-dig in deeper. Out of curiousity, did you have a different version of any of these previously installed, or install any other custom themes?

**Comment by euglevi** [comment]
I installed it once directly within Jupyter Lab, but it was buggy (once in a while the text selection color was not appearing). As I really like Nord theme and it looked as the only one compatible with JL > 2.0, I wanted to give it another shot throught the development version. 

I tried installing it over a clean installation of Jupyter Lab, and it worked! I'm not familiar with npm or yarn, so not sure what happened here.
